username,title,content,status,created_date,issue_date = input(), input(), input(), input(),input() ,input()
print('Имя пользователя:' , username)
print('Заголовок зметки:', title)
print('Описание заметки:', content)
print('Статус заметки:', status)
print('Дата создания заметки:', created_date)
print('Дата истечения заметки:', issue_date)